services:
  web:
    build: .
    container_name: gitlab-webhook
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - WEBHOOK_URL=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=youwechatwebhookkey
      - PORT=5000
    volumes:
      - .:/app